### ISSUE TITLE
PhantomData

### ISSUE THREAD

**Issue by aldanor** [nrc/derive-new#16]
It would be nice if examples like this could be handled automatically if it's even possible:

```rust
#[derive(new)]
pub struct Foo<T> {
    x: u32,
    p: PhantomData<T>,
}

let foo = Foo::<u32>::new(42);  // currently an error since it expects two parameters
```

**Comment by dtolnay** [comment]
:+1: Serde treats PhantomData as a special case as well because it is serializable / deserializable without needing bounds on the type parameter T.

**Comment by kirillkh** [comment]
Came here to file the same issue and, sure enough, it's already filed.
