### ISSUE TITLE
No enum support in crates.io version

### ISSUE THREAD

**Issue by yuri91** [nrc/derive-new#21]
Hi!

I tried to use this crate, and I noticed that the version uploaded on crates.io does not support enums.

I think that the problem is that you did not bump the version of the crate after adding enum support (look at the [history](https://github.com/nrc/derive-new/commits/master/Cargo.toml) of Cargo.toml).

I think you should increment the version to 0.4.1 and issue a `cargo publish`.

Thanks for this useful crate, btw!

**Comment by nrc** [comment]
I published version 0.5 which is today's master, so should work. Thanks for pointing this out!
