### ISSUE TITLE
License file is missing from the crate

### ISSUE THREAD

**Issue by sohankunkerkar** [nrc/derive-new#50]
xref: https://bugzilla.redhat.com/show_bug.cgi?id=1921853#c3

We're in the process of adding this project as a rust-package in Fedora to resolve one of the dependencies for building the `rust-mbrman` package. It would be helpful if someone from the maintainers could add a license file in the [crate](https://crates.io/crates/derive-new) to resolve the fedora packaging standard issue.

/cc @nrc

**Comment by nrc** [comment]
This should be fixed with the 0.5.9 release.
